routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
GET/events, mapped to the index() method,
GET /events/create, mapped to the create() method,
POST /events, mapped to the store() method,
GET /events/{event}, mapped to the show() method,
GET /events/{event}/edit, mapped to the edit() method,
PUT/PATCH /events/{event}, mapped to the update() method,
DELETE /events/{event}, mapped to the destroy() method.
*/
Route::resource('events', 'EventController');

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;

class Event extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'category_id',
        'organiser_id',
        'description',
        'distance',
        'travel_time',
        'school_id',
        'address',
        'date',
        'time',
    ];


}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Event;
use App\Models\Category;
use App\Models\Organiser;
use App\Models\School;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::all();

        return view('events.index', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $userInfo = $this->userInfo();
        return view('events.create',compact('userInfo'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
     {
  
        $request->validate([
            'title'=>'required',
            'category_id'=>'required',
            'description'=>'required',
            'school_id'=>'required'
        ]);

        $addressTo = $request->get('address');
        $addressFrom = $this->getSchoolAddress($request->get('school_id'));
        $mapInfo = $this-> getDistance($addressFrom, $addressTo, $unit = 'K');

        $event = new Event([
            'title' => $request->get('title'),
            'category_id' => $request->get('category_id'),
            'description' => $request->get('description'),
            'school_id' => $request->get('school_id'),
            'date' => $request->get('date'),
            'time' => $request->get('time'),
            'address' => $request->get('address'),
            'organiser_id' => $request->get('organiser_id'),
            'distance' => $mapInfo['distance'],
            'travel_time' => $mapInfo['travel_time']
        ]);

        $event->save();
        return redirect('/events')->with('success', 'Event saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Event::find($id);
        $userInfo = $this->userInfo();
        return view('events.edit', compact('event','userInfo'));       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=>'required',
            'category_id'=>'required',
            'description'=>'required',
            'school_id'=>'required'
        ]);

        $event = Event::find($id);
        $event->title =  $request->get('title');
        $event->category_id = $request->get('category_id');
        $event->description = $request->get('description');
        $event->school_id = $request->get('school_id');
        $event->save();

        return redirect('/events')->with('success', 'Event updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $event = Event::find($id);
        $event->delete();
        return redirect('/events')->with('success', 'Event deleted!');
    }

    private function userInfo(){
        
        $userInfo['categories'] = Category::all();
        $userInfo['orgnisers'] = Organiser::all();
        $userInfo['schools'] = School::all();
        return $userInfo;
    }

    /**
 * @function getDistance()
 * Calculates the distance between two address
 * 
 * @params
 * $addressFrom - Starting point
 * $addressTo - End point
 * $unit - Unit type
 * 
 * @author CodexWorld
 * @url https://www.codexworld.com
 *
 */
function getDistance($addressFrom, $addressTo, $unit = ''){
     
    // Google API key
    $apiKey = 'AIzaSyDdzSlZxREsZwk8H70WufatM2UT3T9Vlo4';
    
    // Change address format
    $formattedAddrFrom    = str_replace(' ', '+', $addressFrom);
    $formattedAddrTo     = str_replace(' ', '+', $addressTo);
    
    // Geocoding API request with start address
    $geocodeFrom = file_get_contents('https://maps.googleapis.com/maps/api/geocode/json?address='.$formattedAddrFrom.'&sensor=false&key='.$apiKey);
    $outputFrom = json_decode($geocodeFrom);
    if(!empty($outputFrom->error_message)){
        return $outputFrom->error_message;
    }
    
    // Geocoding API request with end address
    $geocodeTo = file_get_contents('https://maps.googleapis.com/maps/api/geocode/json?address='.$formattedAddrTo.'&sensor=false&key='.$apiKey);
    $outputTo = json_decode($geocodeTo);
    if(!empty($outputTo->error_message)){
        return $outputTo->error_message;
    }

    // Get latitude and longitude from the geodata
    $latitudeFrom    = $outputFrom->results[0]->geometry->location->lat;
    $longitudeFrom    = $outputFrom->results[0]->geometry->location->lng;
    $latitudeTo        = $outputTo->results[0]->geometry->location->lat;
    $longitudeTo    = $outputTo->results[0]->geometry->location->lng;
    
    // Calculate distance between latitude and longitude
    $theta    = $longitudeFrom - $longitudeTo;
    $dist    = sin(deg2rad($latitudeFrom)) * sin(deg2rad($latitudeTo)) +  cos(deg2rad($latitudeFrom)) * cos(deg2rad($latitudeTo)) * cos(deg2rad($theta));
    $dist    = acos($dist);
    $dist    = rad2deg($dist);
    $miles    = $dist * 60 * 1.1515;

    $mapInfo['distance'] = round($miles * 1.609344, 2).' km';
    
    //travel time 
    
    $data = file_get_contents('https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins='.$formattedAddrFrom.'&destinations='.$formattedAddrTo.'&key='.$apiKey);
    $data = json_decode($data,true);
    $mapInfo['travel_time']  = $data['rows'][0]['elements'][0]['duration']['text'];

    return $mapInfo;
 }


 private function getSchoolAddress($school_id){

    $school = School::find($school_id);
    return $school->address;
 }

}

resources/views/events/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add an Event</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('events.store') }}">
          @csrf
          <div class="form-group">    
              <label for="title">Title:</label>
              <input type="text" class="form-control" name="title"/>
          </div>

          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description"/>
          </div>

          <div class="form-group">
              <label for="address">Address:</label>
              <input type="text" class="form-control" name="address"/>
          </div>

          <div class="form-group"> <!-- Date input -->
            <label class="control-label" for="date">Date</label>
            <input class="form-control" id="date" name="date" placeholder="MM/DD/YYY" type="date"/>
          </div>

          <div class="form-group"> <!-- Date input -->
            <label class="control-label" for="time">Time</label>
            <input class="form-control" id="time" name="time"  type="time"/>
          </div>

          <div class="form-group">
              <label for="category">Category:</label>
              <select class="form-control" name="category_id">
                @foreach($userInfo['categories'] as $category)
                <option value={{$category->id}}>{{$category->title}}</option>
                @endforeach
              </select>
          </div>

          <div class="form-group">
              <label for="organiser">Orgniser:</label>
              <select class="form-control" name="organiser_id">
                @foreach($userInfo['orgnisers'] as $organiser)
                <option value={{$organiser->id}}>{{$organiser->title}}</option>
                @endforeach
              </select>
          </div>

          <div class="form-group">
              <label for="school">Shool::</label>
              <select class="form-control" name="school_id">
                @foreach($userInfo['schools'] as $school)
                <option value={{$school->id}}><b>{{$school->name}}</b> : {{$school->address}}</option>
                @endforeach
              </select>
          </div>

        
                                  
          <button type="submit" class="btn btn-primary">Add Event</button>
      </form>
  </div>
</div>
</div>

@endsection

resources/views/events/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a event</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('events.update', $event->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">    
              <label for="title">Title:</label>
              <input type="text" class="form-control" name="title" value="{{$event->title}}"/>
          </div>

          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description" value="{{$event->description}}"/>
          </div>

          <div class="form-group">
              <label for="address">Address:</label>
              <input type="text" class="form-control" name="address" value="{{$event->address}}"/>
          </div>

          <div class="form-group"> <!-- Date input -->
            <label class="control-label" for="date">Date</label>
            <input class="form-control" id="date" name="date" placeholder="MM/DD/YYY" type="date" value="{{$event->date}}"/>
          </div>

          <div class="form-group"> <!-- Time input -->
            <label class="control-label" for="time">Time</label>
            <input class="form-control" id="time" name="time"  type="time" value="{{$event->time}}"/>
          </div>

          <div class="form-group">
              <label for="category">Category: </label>
              <select class="form-control" name="category_id">
                @foreach($userInfo['categories'] as $category)
                <option value="{{$category->id}}" {{ $event->category_id == $category->id ? 'selected' : '' }}>{{$category->title}}</option>
                @endforeach
              </select>
          </div>

          <div class="form-group">
              <label for="organiser">Orgniser:</label>
              <select class="form-control" name="organiser_id">
                @foreach($userInfo['orgnisers'] as $organiser)
                <option value="{{$organiser->id}}" {{ $event->organiser_id == $organiser->id ? 'selected' : '' }}>{{$organiser->title}}</option>
                @endforeach
              </select>
          </div>

          <div class="form-group">
              <label for="school">Shool::</label>
              <select class="form-control" name="school_id">
                @foreach($userInfo['schools'] as $school)
                <option value={{$school->id}} {{ $event->school_id == $school->id ? 'selected' : '' }}><b>{{$school->name}}</b> : {{$school->address}}</option>
                @endforeach
              </select>
          </div>
      
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/events/index.blade.php
@extends('base')

@section('main')
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
<div>
    <a style="margin: 19px;" href="{{ route('events.create')}}" class="btn btn-primary">New event</a>
    </div>  
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Events</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Title</td>
          <td>Category</td>
          <td>Description</td>
          <td>School</td>
          <td>Distance</td>
          <td>Travel Time</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($events as $event)
        <tr>
            <td>{{$event->id}}</td>
            <td>{{$event->title}} </td>
            <td>{{$event->category_id}}</td>
            <td>{{$event->description}}</td>
            <td>{{$event->school_id}}</td>
            <td>{{$event->distance}}</td>
            <td>{{$event->travel_time}}</td>
            <td>
                <a href="{{ route('events.edit',$event->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('events.destroy', $event->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
@endsection